extends: ../shared_defaults.yaml
run_name: custom_title_abstract_rerank
pipeline: custom_title_abstract_rerank

retrieval:
  type: bm25
  text_mode: title_abstract
  top_k: 1000
  model_name: null

rerank:
  enabled: true
  model_name: cross-encoder/ms-marco-MiniLM-L-12-v2
  candidate_k: 200
  top_k: 200
